### PR TITLE
Update about.md

### PR DESCRIPTION
**Pull request by amandamiotto**

### CODE REVIEW

**Comment by amandamiotto** [comment]
Merged

**Comment by amandamiotto** [comment]
I realised I stuffed up- don't have perms.

**Comment by DamienIrving** [comment]
@amandamiotto Just sent you a collaborator request so that you will have permissions 😄

**Comment by amandamiotto** [comment]
Cheers!


Amanda Miotto | Senior eResearch Analyst


eResearch Services - Digital Solutions

Griffith University/ QCIF | Nathan | QLD 4111

T +61 7 373 54697 | @amandamiottoGU |

 a.miotto@griffith.edu.au

Hacky Hour: Griffith.edu.au/hackyhour | @hackyhourGU



Griffith University - CRICOS Provider Number 00233E


PRIVILEGED - PRIVATE AND CONFIDENTIAL

This email and any files transmitted with it are intended solely for the use of the addressee(s) and may contain information which is confidential or privileged. If you receive this email and you are not the addressee or responsible for delivery of the email to the addressee(s), please disregard the contents of the email, delete the mail and notify the author immediately.


________________________________

**Pull request merged**
